#!/bin/bash
#DEBUG(){
#	[ "$_DEBUG" == "on" ] && $@ || :
#}
randomIP(){
	IP="$(($RANDOM/128))"
	IP=${IP}.$(($RANDOM/128))
	IP=${IP}.$(($RANDOM/128))
	IP=${IP}.$(($RANDOM/128))
	echo $IP
}
sum=1
echo "test create"
echo > test
while [ $sum -le 11 ]
do
	j=$(($RANDOM % 10 + 1))
	echo $j
	addr=$(randomIP)
	echo $addr
	for i in `seq 1 $j`
	do
		 echo -n "$addr" >> test
		 echo -n "$addr"
		 echo '--"GET /epl.shtml HTTP/1.1"302 251 "http://www.404null.com/"' >> test
		 echo "--[$(date +%s)]"GET /epl.shtml HTTP/1.1"302 251 "http://www.404null.com/"" 
	done
		sum=$(($sum+$j))
done
